import { Bank } from "../types";

export const data: Bank[] = [
  {
    ifsc: "ABHY0065001",
    bank_id: 60,
    branch: "RTGS-HO",
    address:
      "ABHYUDAYA BANK BLDG., B.NO.71, NEHRU NAGAR, KURLA (E), MUMBAI-400024",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065002",
    bank_id: 60,
    branch: "ABHYUDAYA NAGAR",
    address:
      "ABHYUDAYA EDUCATION SOCIETY, OPP. BLDG. NO. 18, ABHYUDAYA NAGAR, KALACHOWKY, MUMBAI - 400033",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065003",
    bank_id: 60,
    branch: "BAIL BAZAR",
    address: "KMSPM'S SCHOOL, WADIA ESTATE, BAIL BAZAR-KURLA(W), MUMBAI-400070",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065004",
    bank_id: 60,
    branch: "BHANDUP",
    address: "CHETNA APARTMENTS, J.M.ROAD, BHANDUP, MUMBAI-400078",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065005",
    bank_id: 60,
    branch: "DARUKHANA",
    address: "POTIA IND.ESTATE, REAY ROAD (E), DARUKHANA, MUMBAI-400010",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065006",
    bank_id: 60,
    branch: "FORT",
    address:
      "ABHYUDAYA BANK BLDG., 251, PERIN NARIMAN STREET, FORT, MUMBAI-400001",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065007",
    bank_id: 60,
    branch: "GHATKOPAR",
    address:
      "UNIT NO 2 & 3, SILVER HARMONY BLDG,NEW MANIKLAL ESTATE, GHATKOPAR (WEST), MUMBAI-400086",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065008",
    bank_id: 60,
    branch: "KANJUR",
    address:
      "BHANDARI CO-OP. HSG. SOCIETY, KANJUR VILLAGE, KANJUR (EAST), MUMBAI-400078",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065009",
    bank_id: 60,
    branch: "NEHRU NAGAR",
    address:
      "ABHYUDAYA BANK BLDG., B.NO.71, NEHRU NAGAR, KURLA (E), MUMBAI-400024",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065010",
    bank_id: 60,
    branch: "PAREL",
    address:
      "SHRAMA SAFALYA, 63 G.D.AMBEKAR MARG, PAREL VILLAGE, MUMBAI-400012",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
  {
    ifsc: "ABHY0065011",
    bank_id: 60,
    branch: "SEWRI",
    address:
      "NAVNIDHI INDUSTRIAL ESTATE, ACHARYA DONDHE MARG, SEWRI, MUMBAI-400015",
    city: "MUMBAI",
    district: "GREATER MUMBAI",
    state: "MAHARASHTRA",
    bank_name: "ABHYUDAYA COOPERATIVE BANK LIMITED",
  },
];
